openapi: 3.0.1
info:
  title: monster-hezrou
  x-cortex-tag: monster-hezrou
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: beast
    challenge_rating: 4
    legendary: false
    armor_class: 19
    hit_points: 49
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-hezrou
      alias: github-token-test
